name: OpenSorus Webhook Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull and Run in Conda Environment
        run: |

          rm -rf /home/powerranger/Desktop/aditi/opensorus

          cd /home/powerranger/Desktop/aditi
          git clone https://github.com/aditi-dsi/opensorus.git

          cd /home/powerranger/Desktop/aditi/opensorus

          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate aditi_deploy

          pip install -r requirements.txt

          chmod +x runner.sh
          
          sudo bash runner.sh