name: Deploy Python App via Conda on Local Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull and Run in Conda Environment
        run: |
          cd /home/powerranger/Desktop/aditi/opensorus
          git pull origin main

          # Setup conda
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate aditi_deploy

          # Install dependencies
          pip install -r requirements.txt

          # Restart the systemd service
          sudo bash runner.sh